[options]
Architecture = auto
Color
ParallelDownloads = 5

# 中科大镜像源 (加速下载)
Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
